[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "automap_hxn"
version = "0.1.0"
description = "HXN Beamline AutoMap Wokflow"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.10.0,<10",
    "jupyter>=1.1.1,<2",
    # Tiled's current Numba dependency does not support NumPy 2.5 yet.
    "numpy>=2.4.2,<2.5",
    "pandas>=3.0.0,<4",
    "opencv-python>=4.6.0,<5",
    "scikit-image>=0.26.0,<0.27",
    "tifffile>=2026.1.28,<2027",
    "qtpy>=2.4.3,<3",
    "matplotlib>=3.10.8,<4",
    "tqdm>=4.67,<5",
    "tiled>=0.2.7",
    "bluesky-tiled-plugins>=2.0.2,<3",
    "bluesky-queueserver>=0.0.24,<0.0.25",
    "bluesky-queueserver-api>=0.0.13,<0.0.14",
    "hxntools>=0.6.5,<0.7",
]
authors = [
    { name = "BNL NSLS-II", email = "pattammattel@bnl.gov" },
]
license = { file = "LICENSE" }

[project.optional-dependencies]
segmentation = ["cellpose>=4.0.8,<5", "ultralytics>=8.3,<9", "stardist>=0.9.2,<1", "tensorflow>=2.19,<2.20"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pixi.project]
platforms = ["linux-64", "osx-64", "osx-arm64"]
channels = ["conda-forge"]

[tool.pixi.dependencies]
python = "<3.13"
ipython = ">=9.10.0,<10"
numpy = ">=2.4.2,<2.5"
opencv = ">=4.13,<5"
scikit-image = ">=0.26.0,<0.27"
qtpy = ">=2.4.3,<3"
pyside6 = ">=6.8,<7"
llvmlite = "*"
matplotlib-inline = ">=0.2.1,<0.3"
ipympl = ">=0.10.0,<0.11"
pims = ">=0.7,<0.8"
doct = ">=1.1.0,<2"
bluesky-tiled-plugins = ">=2.0.2,<3"

[tool.pixi.pypi-dependencies]
automap_hxn = {path = ".", editable=true}
tiled = ">0.2.7"
bluesky-queueserver = ">=0.0.24,<0.0.25"
bluesky-queueserver-api = ">=0.0.13,<0.0.14"
cellpose = ">=4.0.8,<5"
hxntools = ">=0.6.5,<0.7"
